#!/bin/bash

# used commands:
export SQLITE=`type -p sqlite3`
export DBFILE=.jash.db
export RM=`type -p rm`
export CAT=`type -p cat`

export PATH=''
export PS1='\u@\h [JAS]$ '

function nieuw_spel () {
	echo -n 'Begin nieuw spel... '
	if test -e $DBFILE; then $RM $DBFILE; fi
	$SQLITE $DBFILE <<-EOF
		CREATE TABLE hand (
				id          INTEGER PRIMARY KEY,
				hun_roem    INTEGER DEFAULT 0,
				hun_punten  INTEGER DEFAULT 0,
				onze_punten INTEGER DEFAULT 0,
				onze_roem   INTEGER DEFAULT 0
				);
		EOF
	echo '[OK]'
}

function nieuwe_hand () {
	echo -n 'Begin nieuwe hand... '
	$SQLITE $DBFILE <<-EOF
		INSERT INTO hand (hun_roem, hun_punten, onze_punten, onze_roem)
		VALUES (0, 0, 0, 0);
	EOF
	echo '[OK]'
}

function delete () {
	echo -n 'Verwijder deze hand...'
	$SQLITE $DBFILE <<-EOF
		DELETE FROM hand
		WHERE rowid=(SELECT MAX(ROWID) FROM hand);
	EOF
	echo '[OK]'
}

function reset () {
	echo -n 'reset deze hand... '
	$SQLITE $DBFILE <<-EOF
		UPDATE hand
		SET hun_roem = 0, hun_punten = 0, onze_punten = 0, onze_roem = 0
		WHERE rowid=(SELECT MAX(ROWID) FROM hand);
	EOF
	echo '[OK]'
}

function list () {
	echo
	echo '        hun     hun     | onze    onze'
	echo 'hand    roem    punten  | punten  roem'
	echo '----------------------------------------'
	$SQLITE $DBFILE <<-EOF
		SELECT
			id || ':	' || hun_roem || '	' || hun_punten || '	| '
			|| onze_punten || '	  ' || onze_roem AS score
		FROM hand
		ORDER BY id;
	EOF
	echo '----------------------------------------'
	$SQLITE $DBFILE <<-EOF
		SELECT
			'	' || SUM(hun_roem) || '	' || SUM(hun_punten) || '	| '
			|| SUM(onze_punten) || '	  ' || SUM(onze_roem) AS score
		FROM hand
		ORDER BY id;
	EOF
	echo
}

function roem () {
	if test $1 = 'h'
	then wiens='hun'
	else wiens='onze'
	fi

	echo -n "$wiens roem += $2... "
	$SQLITE $DBFILE <<-EOF
		UPDATE hand
		SET ${wiens}_roem = ${wiens}_roem + $2
		WHERE rowid=(SELECT MAX(ROWID) FROM hand);
	EOF
	echo '[OK]'
}

function punten () {
	if test $1
	then PUNTEN=$1
	else read -p 'onze punten: ' PUNTEN
	fi

	echo -n "$PUNTEN punten voor ons... "
	$SQLITE $DBFILE <<-EOF
		UPDATE hand
		SET hun_punten = $((162-$PUNTEN)), onze_punten = $PUNTEN
		WHERE rowid=(select max(rowid) from hand);
	EOF
	echo '[OK]'
}

function nat () {
	if test $1 = 'h'
	then wie='zij'; wiens='hun';  anders='onze'
	else wie='wij'; wiens='onze'; anders='hun'
	fi

	echo -n "$wie nat... "
	$SQLITE $DBFILE <<-EOF
		UPDATE hand
		SET ${anders}_roem = ${anders}_roem + ${wiens}_roem,
			${wiens}_roem = 0,
			${anders}_punten = 162
		WHERE rowid=(SELECT MAX(ROWID) FROM hand);
	EOF
	echo '[OK]'
}

# punten zijn bash commands
for ((i=0; i<163; i++))
do alias $i="punten $i; nieuwe_hand"
done

# initialization
nieuw_spel
nieuwe_hand

bind -x '"N":nieuw_spel'         # nieuw spel
bind -x '"n":nieuwe_hand'        # nieuw spel
bind -x '"d":delete; reset'      # verwijder hand
bind -x '"l":list'               # laat score zien
bind -x '"z":roem h 100'         # voeg roem toe
bind -x '"x":roem o 100'
bind -x '"c":roem h 50'
bind -x '"v":roem o 50'
bind -x '"u":roem h 20'
bind -x '"i":roem o 20'
bind -x '"Z":roem h -100'        # haal roem eraf
bind -x '"X":roem o -100'
bind -x '"C":roem h -50'
bind -x '"V":roem o -50'
bind -x '"U":roem h -20'
bind -x '"I":roem o -20'
bind -x '"<":nat o; nieuwe_hand' # wij zijn nat
bind -x '")":nat h; nieuwe_hand' # zij zijn nat
bind -x '"(":nat o; nieuwe_hand' # wij zijn nat
bind -x '">":nat h; nieuwe_hand' # zij zijn nat

